/*************************************************************/
/* Automatically generated by './mkconfig.sh': do note edit! */
/*************************************************************/
#define LGL_OS "Linux DESKTOP-8QSKV4V 6.6.87.2-microsoft-standard-WSL2 x86_64"
#define LGL_COMPILED "Thu Apr 16 22:51:17 CST 2026"
#define LGL_RELEASED "Thu Apr 16 22:51:17 CST 2026"
#define LGL_VERSION "1.0.0"
#define LGL_ID "412c305040af6931d58e9f89d205cd04bfb4bbaa"
