/*************************************************************/
/* Automatically generated by './mkconfig.sh': do note edit! */
/*************************************************************/
#define LGL_OS "Linux DESKTOP-8QSKV4V 6.6.87.2-microsoft-standard-WSL2 x86_64"
#define LGL_COMPILED "Sun Apr 19 12:14:31 CST 2026"
#define LGL_RELEASED "Sun Apr 19 12:14:31 CST 2026"
#define LGL_VERSION "1.0.0"
#define LGL_ID "04e05829a1108c24502e520d85f70d2b57f9e5c8"
