/*************************************************************/
/* Automatically generated by './mkconfig.sh': do note edit! */
/*************************************************************/
#define LGL_OS "Linux DESKTOP-8QSKV4V 6.6.87.2-microsoft-standard-WSL2 x86_64"
#define LGL_COMPILED "Sun Apr 19 13:23:08 CST 2026"
#define LGL_RELEASED "Sun Apr 19 13:23:08 CST 2026"
#define LGL_VERSION "1.0.0"
#define LGL_ID "729d09ebff83cc8ad4b9887920e3ed5fe9ea4f58"
